;; Haskell mode maybe?
(autoload 'haskell-mode "haskell")
(push '("\\.hs\\'" . haskell-mode) auto-mode-alist)
(push '("\\.lhs\\'" . haskell-mode) auto-mode-alist)
(with-eval-after-load "haskell"
  (push "~/.emacs.d/lib/shm/" load-path)
  (require 'haskell-interactive-mode)
  (require 'haskell-process)
  (add-hook 'haskell-mode-hook 'interactive-haskell-mode)
  (when (require 'shm nil)
    (push 'haskell-mode aggressive-indent-excluded-modes)
    (add-hook 'haskell-mode-hook
              (lambda ()
                (haskell-indentation-mode 0)
                (haskell-indent-mode 0)))
    (require 'shm-case-split)
    (define-key shm-map (kbd "C-c C-s") 'shm/case-split)
    (setq shm-program-name "~/.local/bin/structured-haskell-mode")
    (add-hook 'haskell-mode-hook 'structured-haskell-mode))
  ;;  (define-key haskell-mode-map (kbd "C-c C-c") 'haskell-process-cabal-build)
  ;;  (define-key haskell-mode-map (kbd "C-c C-t") 'haskell-process-do-type)
  )
